# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-4908-D226-10/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/Transmit.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/Receive.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/MUX.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/ClockGenerator.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/Address.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/VGA_480640.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/square_clock.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/pixel_generator.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/pixel_clock.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/module_RW.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/I2cSystem.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/TOP_VGA_sprites.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/get_acc.vhd}
      {C:/Users/eleve/Desktop/TP LU/project_final/project_final.srcs/sources_1/new/TOP.vhd}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top TOP
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4908-D226-10/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
