# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ECP/Option-OSY/ComposantProgrammable/communication_system_i2c/CommunicationSystemI2C/accelero/accelero.cache/wt [current_project]
set_property parent.project_path E:/ECP/Option-OSY/ComposantProgrammable/communication_system_i2c/CommunicationSystemI2C/accelero/accelero.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib E:/ECP/Option-OSY/ComposantProgrammable/communication_system_i2c/CommunicationSystemI2C/accelero/accelero.srcs/sources_1/imports/new/module_RW.vhd
read_xdc E:/ECP/Option-OSY/ComposantProgrammable/communication_system_i2c/CommunicationSystemI2C/accelero/accelero.srcs/constrs_1/new/I2C_system.xdc
set_property used_in_implementation false [get_files E:/ECP/Option-OSY/ComposantProgrammable/communication_system_i2c/CommunicationSystemI2C/accelero/accelero.srcs/constrs_1/new/I2C_system.xdc]

catch { write_hwdef -file module_RW.hwdef }
synth_design -top module_RW -part xc7z020clg484-1
write_checkpoint -noxdef module_RW.dcp
catch { report_utilization -file module_RW_utilization_synth.rpt -pb module_RW_utilization_synth.pb }
